### PR TITLE
Add Ubuntu Bionic example

### PR DESCRIPTION
**Pull request by davidcassany**
Ubuntu Bionic is preferred against Xenial to work with KIWI
as it has better dracut adoption than any previous release.

### CODE REVIEW

**Comment by davidcassany** [comment]
@schaefi JFYI un current Ubuntu bionic the `/etc/resolv.conf` file is symlink pointing to a another `resolv.conf` file managed by `systemd-resolved` service. I could not find out which is the expected procedure to create this symlink or if there is any package creating it. In any case I believe it collides with how KIWI handles this file. That's why I included a firstboot service creating it.

Not a big deal, but something to take into account for Ubuntu univers. Making this symlink at build time is not trivial.

**Review by schaefi — APPROVED** [review]
Looks great :+1:

**Comment by schaefi** [comment]
> /etc/resolv.conf file is symlink pointing to a another resolv.conf

:face_with_head_bandage: 

/etc/resolv.conf like /etc/hosts and also /etc/sysconfig/proxy is one of the three special treated files in kiwi. Since we need the host version of it during build time and restore it with the one provided by the distribution or an overlay file

I think the way you did it is good and I really have no better idea which would not imply some unforeseeable after effects

**Comment by davidcassany** [comment]
> I think the way you did it is good and I really have no better idea which would not imply some unforeseeable after effects

I have the same view, otherwise I would have suggested a change... Also I could not find which is the Ubuntu _correct_ way of doing it in a bootstrap procedure (if any). Neither found which package creates it during the installation (again, if there is any), neither managed to configure `network-manager`or other similar tools to create it.

**Pull request merged**
