### PR TITLE
Add Debian-based JeOS images

### PR DESCRIPTION
**Pull request by michal42**

### CODE REVIEW

**Comment by michal42** [comment]
Note that the debian builds need the following repositories to be added to Virtualization:Appliances:CommonBoot:
```
  <repository name="Debian_9.0">
    <path project="Debian:9.0" repository="standard"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
  <repository name="Debian_8.0">
    <path project="Debian:8.0" repository="standard"/>
    <arch>i586</arch>
    <arch>x86_64</arch>
  </repository>
```

**Review by davidcassany — CHANGES_REQUESTED** [review]
Looks good to me, however I noted the Debian 8 repository in CommonBoot is not there yet, which should not be complex to include unless debian specific issues arise.

Also I noted you use xenial oemboot for the oem image type, I would not do so, this leads to confusion in my opinion, if the oemboot code of debian based distros can be shared this needs to be reflected into the `kiwi/boot` code by linking/copying them or by having specific debian boot code in addition to the ubuntu xenial one.

I could successfully test vmx image, this one works great. The iso image failed due to not being capable to find isolinux.bin binary and the oem image needs to include a package providing a kernel, as there is a runtime check that forces us to clearly state which kernel to use, this is tricky because since oem ubuntu boot code is used, the runtime check looks for a "linux-generic" package which in Debian is called "linux-image" if I am not mistaken.

I suggest to start only with vmx description in this PR as this is already working and leave the others for future PRs once the above mentioned issues are fixed.

**Comment by michal42** [comment]
Fair enough. I will submit with only the vmx type included. Re CommonBoot repos, that's what I wrote above, these need to be added. I'm testing with my buildservice branch (home:michal-m:branches:Virtualization:Appliances:CommonBoot) and the packages build OK against Debian 8/9

**Comment by davidcassany** [comment]
@michal42, good I'll try to get CommonBoot for Debian 8/9, I believe it won't be really difficult to make other types work, but better if we go step by step. Also it will be easier to check and validate.

Thanks

**Comment by michal42** [comment]
https://github.com/SUSE/kiwi-descriptions/pull/10

**Pull request closed without merging**
