### PR TITLE
Update meta packages for the buildservice

### PR DESCRIPTION
**Pull request by schaefi**
After a discussion with Rudi I got a better understanding how the provides information is created from the build script code. The build script code creates provides tags from the XML attributes
boot, image and filesystem. 

* The kiwi-boot-requires package has been changed to be only mapped to the provides tags created from the boot attribute.

* Additional meta packages to be mapped to the provides tags from the image attributes has been added.
* A collective meta package for the filesystem attribute has also been added and is referenced in the image meta packages which also needs filesystems.

The new structure will also allow to drop kiwi-boot-requires at some point in the future in a clean way without loosing the other provides/package mapping

### CODE REVIEW

**Comment by davidcassany** [comment]
I like this modular approach of having several meta packages requiring the appropriate tools depending on image type. :+1:

**Comment by schaefi** [comment]
Thanks I think this is the way to go, but I'd like to have the obs people a look, will go upstairs and grab them again :)

**Review by adrianschroeter — APPROVED** [review]
yep, good approach :)

haven't looked into details, but should be fine in general:)

**Review by bugfinder — APPROVED** [review]
looks very good, go for it!

**Pull request merged**
