### PR TITLE
Adding Leap 15.1 oemboot and netboot descriptions

### PR DESCRIPTION
**Pull request by davidcassany**
Fixes boo#1132839

### CODE REVIEW

**Comment by davidcassany** [comment]
@schaefi this is the fix for https://bugzilla.suse.com/show_bug.cgi?id=1132839 The file `kiwi-boot-package` will be generated accordingly after this PR gets merged.

I copied the descriptions from Leap 15.0 and renamed it to Leap 15.1. I tried to build and boot an oem image using the appropriate oemboot initrd for x86_64. I also validated a pxe image using netboot/suse-leap15.1 builds.

**Comment by schaefi** [comment]
Hmm, do we really want to populate Leap15.1 oemboot descriptions ? I think this is a good opportunity to make people move on dracut for oem images. For netboot I think we have no other choice because customers can not easily change their PXE boot infrastructure.

Is the bug explicitly stating that some group in SUSE needs oemboot/suse-leap15.1 ? All the people contacting me with the problem on oemboot just copied old image descriptions and where happy with the move to dracut. I also think the oemboot code is not working well since its not been tested

Thoughts ?

**Comment by davidcassany** [comment]
> Hmm, do we really want to populate Leap15.1 oemboot descriptions ?

Yes, I was wondering also about that. The bug does not explicitly states the need of oemboot, in fact the bug just complaints of missing leap 15.1 specific entries in `kiwi-boot-package` file, as it causes the build of `kiwi-boot-descriptions` package to break for leap 15.1.

> I also think the oemboot code is not working well since its not been tested

yes this is my concern about this PR, we have not a reasonable way to test it.

I'd be fine by dropping oemboot support for leap 15.1. This way we have only support for x86_64 netboot. The oemboot code for arm scares me.

I am updating the PR

**Comment by davidcassany** [comment]
Now only netboot has been added for leap 15.1

**Comment by schaefi** [comment]
> I'd be fine by dropping oemboot support for leap 15.1

yep let's do that, it will only strike back and I rather convince people to use dracut

> The oemboot code for arm scares me.

I doubt anything of that will work on arm, no tests and no Alex Graf anymore that has an eye on it.
I'm testing arm with raspberry and dracut and also in Amazon EC2 for the arm instances. No other board is on my plate. I really doubt that oemboot code will work

It's time to get rid of all that :)

**Review by schaefi — APPROVED** [review]
Looks good now :+1: 

feel free to merge and go ahead with the package update. Thanks much

**Pull request merged**
