### PR TITLE
Add Debian buster and Ubuntu Focal examples

### PR DESCRIPTION
**Pull request by davidcassany**
This commit adds Debian Buster and Ubuntu Focal image description
examples. In addition it also removes old versions for Debian and Ubuntu
and it updates the Arch repositories for the Arch Linux example.

### CODE REVIEW

**Comment by davidcassany** [comment]
@schaefi I added the discussion label since this PR starts using the schema 7.2 for the new Ubuntu Focal and Debian Buster images. At the time I had already prepared and tested the images I noted the 7.2 schema is not yet released and, beyond the fact that we should not publish examples that makes use of sutff that is not yet released, that made me wonder if this is actually a good a idea to include a very recent schema definition in examples, as only users using upstream versions are capable to use them without having to adapt the descriptions, and description downgrade is not obvious. I know it is a minor thing, but that made wonder if we shouldn't try to have a criteria on that.

**Comment by schaefi** [comment]
I think it makes sense to keep the examples at schema version 6.8. Currently all examples are using that schema and this allows people to build with older kiwi-ng versions too. This of course only works if no feature of the newer schema is used.

**Review by schaefi — CHANGES_REQUESTED** [review]
I would use schema 6.8 and stay in line with the other image descriptions

**Comment by davidcassany** [comment]
> I would use schema 6.8 and stay in line with the other image descriptions

Yes makes sense. Just updated it.

**Review by schaefi — APPROVED** [review]

**Pull request merged**
