### PR TITLE
No more boot code for Leap 15.2

### PR DESCRIPTION
**Pull request by davidcassany**
Fixes bsc#1145724

### CODE REVIEW

**Comment by davidcassany** [comment]
I have just ported (copied) the Leap 15.1 descriptions to Leap15.2, at the current stage there isn't much more we can do. Also 15.2 is in very early stages and with almost no bias from 15.1.

**Comment by schaefi** [comment]
Needs clarification on the use case

**Comment by davidcassany** [comment]
@schaefi, some clarifications on the use case have been made in [bsc#1145724](https://bugzilla.suse.com/show_bug.cgi?id=1145724), I believe it is time for us to decide if we completely drop support for PXE type of Leap 15.2 images in favor of disk based deployments or we still keep them.

I think it is a good chance for us to stop providing Leap 15.2 PXE image boot description. This way we already collect some experience on helping users to move to disk based deployments before we completely drop the whole PXE type (I'd say it would be nice for SLE16 so SLE15 time frame is the transition period).

I adapted the PR to reflect how I'd do it, in any case we still need to agree on how custom boot is supported for leap 15.2. I'd say no custom boot at all, since in Leap 15.1 we only had netboot left and up to my knowledge this is not being used in Leap 15.1 or Leap 15.2.

**Comment by schaefi** [comment]
> I think it is a good chance for us to stop providing Leap 15.2 PXE

I fully agree :+1:

**Review by schaefi — APPROVED** [review]

**Pull request merged**
