### PR TITLE
Add Debian-based JeOS images v2

### PR DESCRIPTION
**Pull request by michal42**
Changes in v2:
 - Removed iso and oem build types for now
 - Actually build the Stretch image from Stretch packages

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
Looks good to me 👍

**Comment by davidcassany** [comment]
@schaefi, this comes from #9, this update requires to include Debian 8/9 repositories in CommonBoot project, as @michal42 suggested in the comments there. Could you include these repositories?

**Comment by schaefi** [comment]
I'll take a look as soon as the next free slot arrives :)

**Comment by schaefi** [comment]
Ok, done all common boot packages now also builds for Debian 8 and 9

**Pull request merged**
